name = "Redis"
uuid = "0cf705f9-a9e2-50d1-a699-2b372a39b750"
version = "3.0.1"

[deps]
AwsIO = "4047365c-aa37-44ec-b1fa-4c0d5495ccf1"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Harbor = "af79dbb9-1a80-47ad-8928-192a4af69376"

[targets]
test = ["Harbor", "Test"]
